sudo: required
language: node_js
services:
  - docker
node_js:
  - "5.1"
after_success:
  - docker build -t frisches/fr_mothership .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push frisches/fr_mothership
notifications:
  slack:
    rooms:
      - frisches:u6xDE2UFlFJqyWZQPR3pXPm4#engineering